---
version: '2'
services: 
    activemq:
       image: webcenter/activemq:latest
       environment:
         ACTIVEMQ_NAME: amq
       ports:
         - "8161:8161"
         - "61616:61616"
         - "61613:61613"
       volumes:
         - "amqdata:/data/activemq"
         - "log:/var/log/activemq"
         - "conf:/opt/activemq/conf"
       networks:
         - activemq-net

volumes:
     amqdata:
     log:
     conf:
 
networks:
   activemq-net: