version: '2'
services:
  myproject:
    container_name: myProject
    build: .
    command: "npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/home/app/myProject
      - /home/app/myProject/node_modules
