#!/usr/bin/env bash
set -euo pipefail

# ==============================================
#  EXPORT SYSTEM LOGS (Ubuntu / Kubuntu)
#  Author: Yannis (auto-generated by ChatGPT)
# ==============================================

# 1️⃣ Define export location and filenames
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
EXPORT_DIR="$PWD/system-logs-$TIMESTAMP"
ARCHIVE_NAME="system-logs-$TIMESTAMP.tar.gz"

echo "🧾 Collecting system logs into: $EXPORT_DIR"
mkdir -p "$EXPORT_DIR"

# 2️⃣ Save general system info
echo "📋 Saving system info..."
{
  echo "=== System Information ==="
  hostnamectl
  echo ""
  echo "=== Uptime ==="
  uptime
  echo ""
  echo "=== Kernel & OS ==="
  uname -a
  echo ""
  echo "=== Network Interfaces ==="
  ip link
  echo ""
  echo "=== Wi-Fi Devices ==="
  nmcli device status
  echo ""
  echo "=== Routes ==="
  ip route
} > "$EXPORT_DIR/system_info.txt"

# 3️⃣ Export journal logs
echo "🧠 Exporting journal logs..."
sudo journalctl -b > "$EXPORT_DIR/journal_boot.txt"
sudo journalctl -u NetworkManager > "$EXPORT_DIR/journal_networkmanager.txt"
sudo journalctl -k > "$EXPORT_DIR/journal_kernel.txt"

# 4️⃣ Copy classic log files (if they exist)
echo "📚 Copying log files..."
LOG_PATHS=(
  "/var/log/syslog"
  "/var/log/kern.log"
  "/var/log/auth.log"
  "/var/log/dmesg"
  "/var/log/Xorg.0.log"
  "/var/log/apt"
  "/var/log/dpkg.log"
  "/var/log/NetworkManager"
)
for path in "${LOG_PATHS[@]}"; do
  if [ -e "$path" ]; then
    sudo cp -r "$path" "$EXPORT_DIR/" 2>/dev/null || true
  fi
done

# 5️⃣ Include Wi-Fi and network diagnostics
echo "📡 Running Wi-Fi diagnostics..."
{
  echo "=== Active Wi-Fi ==="
  nmcli -f GENERAL,IP4,IP6 dev show wlp1s0 2>/dev/null || true
  echo ""
  echo "=== Wi-Fi scan summary ==="
  nmcli -f SSID,SECURITY,SIGNAL,BARS dev wifi list 2>/dev/null || true
  echo ""
  echo "=== Driver details ==="
  lspci -nnk | grep -A3 -i network
  echo ""
  echo "=== Loaded kernel modules for Wi-Fi ==="
  lsmod | grep iwlwifi || true
  echo ""
  echo "=== dmesg Wi-Fi logs ==="
  sudo dmesg | grep -i wlp1s0 | tail -n 100
} > "$EXPORT_DIR/network_diagnostics.txt"

# 6️⃣ Compress everything
echo "📦 Creating archive: $ARCHIVE_NAME"
sudo tar -czf "$ARCHIVE_NAME" -C "$EXPORT_DIR" .
OWNER="${SUDO_USER:-$USER}"
sudo chown "$OWNER":"$OWNER" "$ARCHIVE_NAME" 2>/dev/null || true


# 7️⃣ Show summary
echo "✅ Done!"
echo "Logs collected and compressed into: $PWD/$ARCHIVE_NAME"
echo "To inspect:  tar -tzf $ARCHIVE_NAME"
