version: '2'
services: 
    db:
       build: postgresql
       environment: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
       ports:
         - "5432:5432"

    wildfly:
       build: keycloak
       depends_on:
         - db
       ports: 
         - "8080:8080"
         - "8787:8787"
         - "9990:9990"
       volumes: 
         - "wildfly_deployments:/opt/jboss/keycloak/standalone/deployments"
         - "wildfly_logs:/opt/jboss/keycloak/standalone/log"
         - "acts_static:/opt/jboss/static"

volumes: 
     wildfly_logs: 
     wildfly_deployments: 
     acts_static: 
