---
version: '3'
services:
   nginx:
      build: 
         context: ./proxy/
         args:
            SERVER_IP: ${SERVER_IP}
            PORTAINER_PORT: ${PORTAINER_PORT}
            WORDPRESS_PORT: ${WORDPRESS_PORT}
      ports:
         - 80:80
         - 443:443
      volumes:        
         - ./nginx-html:/var/www/html        
      networks:
         - net
networks:
   net:
   
