version: '2'
services: 
   portainer:
      image: portainer/portainer
      ports:
         - 9000:9000      
      privileged: true
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - net
      
networks:
    net:
